dist: bionic
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk15
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      jdk: openjdk8
script:
  - ./mvnw install -DskipTests=true 
  - ./mvnw test
